# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-codebuild
  description: Terraform Module to easily leverage AWS CodeBuild for Continuous Integration
  homepage: https://cloudposse.com/accelerate
  topics: terraform, codebuild, terraform-modules, continuous-integration, cicd, aws, hcl2


